// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLMfSwtb0tW3u0Yy3E-Xzqf7AYVneMYr4',
    appId: '1:573803180465:web:082e885bb0a26053338d90',
    messagingSenderId: '573803180465',
    projectId: 'yessir-ab94c',
    authDomain: 'yessir-ab94c.firebaseapp.com',
    storageBucket: 'yessir-ab94c.firebasestorage.app',
    measurementId: 'G-T3V8D3ZYM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgKfVcMQqIsQesJTGfnacLhMkyuvXlCdc',
    appId: '1:573803180465:android:e5ea6ebb637394a6338d90',
    messagingSenderId: '573803180465',
    projectId: 'yessir-ab94c',
    storageBucket: 'yessir-ab94c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCADW-p8q7h1kfMHU_s7lORVUY12BF-8vw',
    appId: '1:573803180465:ios:80cdf6fece3ada1a338d90',
    messagingSenderId: '573803180465',
    projectId: 'yessir-ab94c',
    storageBucket: 'yessir-ab94c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCADW-p8q7h1kfMHU_s7lORVUY12BF-8vw',
    appId: '1:573803180465:ios:80cdf6fece3ada1a338d90',
    messagingSenderId: '573803180465',
    projectId: 'yessir-ab94c',
    storageBucket: 'yessir-ab94c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLMfSwtb0tW3u0Yy3E-Xzqf7AYVneMYr4',
    appId: '1:573803180465:web:4454e7f5e3742022338d90',
    messagingSenderId: '573803180465',
    projectId: 'yessir-ab94c',
    authDomain: 'yessir-ab94c.firebaseapp.com',
    storageBucket: 'yessir-ab94c.firebasestorage.app',
    measurementId: 'G-DDGF5KQMHJ',
  );
}
